name: ecommerce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_spinkit: ^5.1.0
  freezed: ^0.15.0+1
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  lottie: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1

flutter:

  uses-material-design: true
